export const GLOBAL_DEFAULTS: Record<string, string> = {
  'settings.logo': '/logo-figma.svg',
  'settings.hotel_name': 'Golden Carthage',
  'settings.hotel_tagline': 'Hôtel & Résidence',
  'settings.address': 'Avenue de la Promenade - Gammarth, Tunis',
  'settings.phone': '+216.71.913.000',
  'settings.phone_secondary': '',
  'settings.email': 'info@goldencarthage.com',
  'settings.email_reservations': 'reservations@goldencarthage.com',
  'settings.social_facebook': 'https://facebook.com/goldencarthage',
  'settings.social_instagram': 'https://instagram.com/goldencarthage',
  'settings.social_youtube': 'https://youtube.com/@goldencarthage',
  'settings.social_pinterest': '',
  'settings.instagram_gallery_url': 'https://instagram.com/goldencarthage',
  'settings.app_store_url': '',
  'settings.google_play_url': '',
  'footer.logo': '/imgs/GCH.svg',
  'footer.about': 'Golden Carthage Hôtel & Résidence Tunis est situé sur la magnifique baie de Gammarth, surplombant les eaux cristallines de la mer méditerranée.',
  'footer.newsletter_placeholder': 'Votre adresse e-mail',
}
