export interface PhoneCountry {
  iso: string
  dial: string
  label: string
}

export const PHONE_COUNTRIES: PhoneCountry[] = [
  { iso: 'tn', dial: '+216', label: 'Tunisie' },
  { iso: 'fr', dial: '+33', label: 'France' },
  { iso: 'gb', dial: '+44', label: 'Royaume-Uni' },
  { iso: 'de', dial: '+49', label: 'Allemagne' },
  { iso: 'it', dial: '+39', label: 'Italie' },
  { iso: 'es', dial: '+34', label: 'Espagne' },
  { iso: 'be', dial: '+32', label: 'Belgique' },
  { iso: 'ch', dial: '+41', label: 'Suisse' },
  { iso: 'ma', dial: '+212', label: 'Maroc' },
  { iso: 'dz', dial: '+213', label: 'Algérie' },
  { iso: 'ly', dial: '+218', label: 'Libye' },
  { iso: 'eg', dial: '+20', label: 'Égypte' },
  { iso: 'sa', dial: '+966', label: 'Arabie saoudite' },
  { iso: 'ae', dial: '+971', label: 'Émirats arabes unis' },
  { iso: 'qa', dial: '+974', label: 'Qatar' },
  { iso: 'kw', dial: '+965', label: 'Koweït' },
  { iso: 'us', dial: '+1', label: 'États-Unis' },
  { iso: 'ca', dial: '+1', label: 'Canada' },
  // --- separator: all other countries alphabetically ---
  { iso: 'af', dial: '+93', label: 'Afghanistan' },
  { iso: 'al', dial: '+355', label: 'Albanie' },
  { iso: 'ad', dial: '+376', label: 'Andorre' },
  { iso: 'ao', dial: '+244', label: 'Angola' },
  { iso: 'ag', dial: '+1-268', label: 'Antigua-et-Barbuda' },
  { iso: 'ar', dial: '+54', label: 'Argentine' },
  { iso: 'am', dial: '+374', label: 'Arménie' },
  { iso: 'au', dial: '+61', label: 'Australie' },
  { iso: 'at', dial: '+43', label: 'Autriche' },
  { iso: 'az', dial: '+994', label: 'Azerbaïdjan' },
  { iso: 'bs', dial: '+1-242', label: 'Bahamas' },
  { iso: 'bh', dial: '+973', label: 'Bahreïn' },
  { iso: 'bd', dial: '+880', label: 'Bangladesh' },
  { iso: 'bb', dial: '+1-246', label: 'Barbade' },
  { iso: 'by', dial: '+375', label: 'Biélorussie' },
  { iso: 'bz', dial: '+501', label: 'Belize' },
  { iso: 'bj', dial: '+229', label: 'Bénin' },
  { iso: 'bt', dial: '+975', label: 'Bhoutan' },
  { iso: 'bo', dial: '+591', label: 'Bolivie' },
  { iso: 'ba', dial: '+387', label: 'Bosnie-Herzégovine' },
  { iso: 'bw', dial: '+267', label: 'Botswana' },
  { iso: 'br', dial: '+55', label: 'Brésil' },
  { iso: 'bn', dial: '+673', label: 'Brunei' },
  { iso: 'bg', dial: '+359', label: 'Bulgarie' },
  { iso: 'bf', dial: '+226', label: 'Burkina Faso' },
  { iso: 'bi', dial: '+257', label: 'Burundi' },
  { iso: 'cv', dial: '+238', label: 'Cap-Vert' },
  { iso: 'kh', dial: '+855', label: 'Cambodge' },
  { iso: 'cm', dial: '+237', label: 'Cameroun' },
  { iso: 'cf', dial: '+236', label: 'Centrafrique' },
  { iso: 'td', dial: '+235', label: 'Tchad' },
  { iso: 'cl', dial: '+56', label: 'Chili' },
  { iso: 'cn', dial: '+86', label: 'Chine' },
  { iso: 'co', dial: '+57', label: 'Colombie' },
  { iso: 'km', dial: '+269', label: 'Comores' },
  { iso: 'cg', dial: '+242', label: 'Congo' },
  { iso: 'cd', dial: '+243', label: 'Congo (RDC)' },
  { iso: 'cr', dial: '+506', label: 'Costa Rica' },
  { iso: 'hr', dial: '+385', label: 'Croatie' },
  { iso: 'cu', dial: '+53', label: 'Cuba' },
  { iso: 'cy', dial: '+357', label: 'Chypre' },
  { iso: 'cz', dial: '+420', label: 'Tchéquie' },
  { iso: 'dk', dial: '+45', label: 'Danemark' },
  { iso: 'dj', dial: '+253', label: 'Djibouti' },
  { iso: 'dm', dial: '+1-767', label: 'Dominique' },
  { iso: 'do', dial: '+1-809', label: 'Rép. dominicaine' },
  { iso: 'ec', dial: '+593', label: 'Équateur' },
  { iso: 'sv', dial: '+503', label: 'El Salvador' },
  { iso: 'gq', dial: '+240', label: 'Guinée équatoriale' },
  { iso: 'er', dial: '+291', label: 'Érythrée' },
  { iso: 'ee', dial: '+372', label: 'Estonie' },
  { iso: 'sz', dial: '+268', label: 'Eswatini' },
  { iso: 'et', dial: '+251', label: 'Éthiopie' },
  { iso: 'fj', dial: '+679', label: 'Fidji' },
  { iso: 'fi', dial: '+358', label: 'Finlande' },
  { iso: 'ga', dial: '+241', label: 'Gabon' },
  { iso: 'gm', dial: '+220', label: 'Gambie' },
  { iso: 'ge', dial: '+995', label: 'Géorgie' },
  { iso: 'gh', dial: '+233', label: 'Ghana' },
  { iso: 'gr', dial: '+30', label: 'Grèce' },
  { iso: 'gd', dial: '+1-473', label: 'Grenade' },
  { iso: 'gt', dial: '+502', label: 'Guatemala' },
  { iso: 'gn', dial: '+224', label: 'Guinée' },
  { iso: 'gw', dial: '+245', label: 'Guinée-Bissau' },
  { iso: 'gy', dial: '+592', label: 'Guyana' },
  { iso: 'ht', dial: '+509', label: 'Haïti' },
  { iso: 'hn', dial: '+504', label: 'Honduras' },
  { iso: 'hu', dial: '+36', label: 'Hongrie' },
  { iso: 'in', dial: '+91', label: 'Inde' },
  { iso: 'id', dial: '+62', label: 'Indonésie' },
  { iso: 'ir', dial: '+98', label: 'Iran' },
  { iso: 'iq', dial: '+964', label: 'Irak' },
  { iso: 'ie', dial: '+353', label: 'Irlande' },
  { iso: 'il', dial: '+972', label: 'Israël' },
  { iso: 'jm', dial: '+1-876', label: 'Jamaïque' },
  { iso: 'jp', dial: '+81', label: 'Japon' },
  { iso: 'jo', dial: '+962', label: 'Jordanie' },
  { iso: 'kz', dial: '+7', label: 'Kazakhstan' },
  { iso: 'ke', dial: '+254', label: 'Kenya' },
  { iso: 'ki', dial: '+686', label: 'Kiribati' },
  { iso: 'kp', dial: '+850', label: 'Corée du Nord' },
  { iso: 'kr', dial: '+82', label: 'Corée du Sud' },
  { iso: 'kg', dial: '+996', label: 'Kirghizistan' },
  { iso: 'la', dial: '+856', label: 'Laos' },
  { iso: 'lv', dial: '+371', label: 'Lettonie' },
  { iso: 'lb', dial: '+961', label: 'Liban' },
  { iso: 'ls', dial: '+266', label: 'Lesotho' },
  { iso: 'lr', dial: '+231', label: 'Libéria' },
  { iso: 'li', dial: '+423', label: 'Liechtenstein' },
  { iso: 'lt', dial: '+370', label: 'Lituanie' },
  { iso: 'lu', dial: '+352', label: 'Luxembourg' },
  { iso: 'mg', dial: '+261', label: 'Madagascar' },
  { iso: 'mw', dial: '+265', label: 'Malawi' },
  { iso: 'my', dial: '+60', label: 'Malaisie' },
  { iso: 'mv', dial: '+960', label: 'Maldives' },
  { iso: 'ml', dial: '+223', label: 'Mali' },
  { iso: 'mt', dial: '+356', label: 'Malte' },
  { iso: 'mh', dial: '+692', label: 'Marshall' },
  { iso: 'mr', dial: '+222', label: 'Mauritanie' },
  { iso: 'mu', dial: '+230', label: 'Maurice' },
  { iso: 'mx', dial: '+52', label: 'Mexique' },
  { iso: 'fm', dial: '+691', label: 'Micronésie' },
  { iso: 'md', dial: '+373', label: 'Moldavie' },
  { iso: 'mc', dial: '+377', label: 'Monaco' },
  { iso: 'mn', dial: '+976', label: 'Mongolie' },
  { iso: 'me', dial: '+382', label: 'Monténégro' },
  { iso: 'mz', dial: '+258', label: 'Mozambique' },
  { iso: 'mm', dial: '+95', label: 'Myanmar' },
  { iso: 'na', dial: '+264', label: 'Namibie' },
  { iso: 'nr', dial: '+674', label: 'Nauru' },
  { iso: 'np', dial: '+977', label: 'Népal' },
  { iso: 'nl', dial: '+31', label: 'Pays-Bas' },
  { iso: 'nz', dial: '+64', label: 'Nouvelle-Zélande' },
  { iso: 'ni', dial: '+505', label: 'Nicaragua' },
  { iso: 'ne', dial: '+227', label: 'Niger' },
  { iso: 'ng', dial: '+234', label: 'Nigeria' },
  { iso: 'mk', dial: '+389', label: 'Macédoine du Nord' },
  { iso: 'no', dial: '+47', label: 'Norvège' },
  { iso: 'om', dial: '+968', label: 'Oman' },
  { iso: 'pk', dial: '+92', label: 'Pakistan' },
  { iso: 'pw', dial: '+680', label: 'Palaos' },
  { iso: 'pa', dial: '+507', label: 'Panama' },
  { iso: 'pg', dial: '+675', label: 'Papouasie-Nvelle-Guinée' },
  { iso: 'py', dial: '+595', label: 'Paraguay' },
  { iso: 'pe', dial: '+51', label: 'Pérou' },
  { iso: 'ph', dial: '+63', label: 'Philippines' },
  { iso: 'pl', dial: '+48', label: 'Pologne' },
  { iso: 'pt', dial: '+351', label: 'Portugal' },
  { iso: 'ps', dial: '+970', label: 'Palestine' },
  { iso: 'ro', dial: '+40', label: 'Roumanie' },
  { iso: 'ru', dial: '+7', label: 'Russie' },
  { iso: 'rw', dial: '+250', label: 'Rwanda' },
  { iso: 'kn', dial: '+1-869', label: 'Saint-Kitts-et-Nevis' },
  { iso: 'lc', dial: '+1-758', label: 'Sainte-Lucie' },
  { iso: 'vc', dial: '+1-784', label: 'Saint-Vincent' },
  { iso: 'ws', dial: '+685', label: 'Samoa' },
  { iso: 'sm', dial: '+378', label: 'Saint-Marin' },
  { iso: 'st', dial: '+239', label: 'São Tomé-et-Príncipe' },
  { iso: 'sn', dial: '+221', label: 'Sénégal' },
  { iso: 'rs', dial: '+381', label: 'Serbie' },
  { iso: 'sc', dial: '+248', label: 'Seychelles' },
  { iso: 'sl', dial: '+232', label: 'Sierra Leone' },
  { iso: 'sg', dial: '+65', label: 'Singapour' },
  { iso: 'sk', dial: '+421', label: 'Slovaquie' },
  { iso: 'si', dial: '+386', label: 'Slovénie' },
  { iso: 'sb', dial: '+677', label: 'Salomon' },
  { iso: 'so', dial: '+252', label: 'Somalie' },
  { iso: 'za', dial: '+27', label: 'Afrique du Sud' },
  { iso: 'ss', dial: '+211', label: 'Soudan du Sud' },
  { iso: 'sd', dial: '+249', label: 'Soudan' },
  { iso: 'sr', dial: '+597', label: 'Suriname' },
  { iso: 'se', dial: '+46', label: 'Suède' },
  { iso: 'sy', dial: '+963', label: 'Syrie' },
  { iso: 'tw', dial: '+886', label: 'Taïwan' },
  { iso: 'tj', dial: '+992', label: 'Tadjikistan' },
  { iso: 'tz', dial: '+255', label: 'Tanzanie' },
  { iso: 'th', dial: '+66', label: 'Thaïlande' },
  { iso: 'tl', dial: '+670', label: 'Timor-Leste' },
  { iso: 'tg', dial: '+228', label: 'Togo' },
  { iso: 'to', dial: '+676', label: 'Tonga' },
  { iso: 'tt', dial: '+1-868', label: 'Trinité-et-Tobago' },
  { iso: 'tr', dial: '+90', label: 'Turquie' },
  { iso: 'tm', dial: '+993', label: 'Turkménistan' },
  { iso: 'tv', dial: '+688', label: 'Tuvalu' },
  { iso: 'ug', dial: '+256', label: 'Ouganda' },
  { iso: 'ua', dial: '+380', label: 'Ukraine' },
  { iso: 'uy', dial: '+598', label: 'Uruguay' },
  { iso: 'uz', dial: '+998', label: 'Ouzbékistan' },
  { iso: 'vu', dial: '+678', label: 'Vanuatu' },
  { iso: 've', dial: '+58', label: 'Venezuela' },
  { iso: 'vn', dial: '+84', label: 'Viêt Nam' },
  { iso: 'ye', dial: '+967', label: 'Yémen' },
  { iso: 'zm', dial: '+260', label: 'Zambie' },
  { iso: 'zw', dial: '+263', label: 'Zimbabwe' },
]

export function countryFlagSrc(iso: string): string {
  return `/imgs/svgflags/${iso}.svg`
}

export function findPhoneCountry(iso: string): PhoneCountry {
  return PHONE_COUNTRIES.find(c => c.iso === iso) ?? PHONE_COUNTRIES[0]
}
